traces
| where customDimensions.EventName == "WorkflowTriggerEnd"
| where customDimensions.prop__status == "Failed"
| extend resource =  parse_json(tostring(parse_json(tostring(customDimensions.prop__properties)).resource))
| project timestamp 
        , LogicApp = tostring(cloud_RoleName)
        , Workflow = tostring(resource.workflowName)
        | summarize Count = count()
by bin(timestamp, 1d),
        Workflow
| render barchart
| sort by timestamp desc 

